namespace IsaacAgent.Core.Knowledge;

public static class IsaacClasses
{
    public static readonly Dictionary<string, ClassInfo> Classes = new()
    {
        ["Isaac"] = new("Global", "Core API functions for entity spawning, room queries, and general utilities.", new[]
        {
            "Isaac.GetPlayer() — Returns the player EntityPlayer (player 0).",
            "Isaac.GetPlayer(idx) — Returns player by index (for co-op).",
            "Isaac.GetRandomPlayer() — Returns a random player entity.",
            "Isaac.GetRoomEntities() — Returns table of all entities in current room.",
            "Isaac.GetEntities() — Returns table of all entities in the game.",
            "Isaac.Spawn(type, variant, subtype, position, velocity, spawner) — Spawns an entity.",
            "Isaac.FindInRadius(position, radius, partitions) — Finds entities in radius.",
            "Isaac.FindByType(type, variant, subtype) — Finds entities by type.",
            "Isaac.GetFreeNearPosition(position, radius) — Finds free position near point.",
            "Isaac.GetTextWidth() — Gets rendered text width.",
            "Isaac.RenderText() — Renders text on screen.",
            "Isaac.SetDungeonTemplateIdx() — Sets dungeon template index.",
            "Isaac.GetMaxTrinkets() — Returns max trinket ID + 1.",
            "Isaac.GetMaxCards() — Returns max card ID + 1.",
            "Isaac.GetMaxPills() — Returns max pill ID + 1.",
        }),
        ["Game"] = new("Global", "Game state access via Game(). Provides level, room, and game-wide data.", new[]
        {
            "Game() — Returns the Game object.",
            "game:GetLevel() — Returns the Level object.",
            "game:GetRoom() — Returns the Room object.",
            "game:GetSeeds() — Returns the Seeds object.",
            "game:GetItemPool() — Returns the ItemPool object.",
            "game:GetDevilRoomDeals() — Returns number of devil room deals taken.",
            "game:StartNewGame() — Starts a new game.",
            "game:IsGreedMode() — Returns true if greed mode.",
            "game:IsHardMode() — Returns true if hard mode.",
            "game:GetFrameCount() — Returns total frame count.",
            "game:GetTime() — Returns game time in ms.",
            "game:Spawn(type, variant, pos, vel, spawner, subtype, seed) — Spawns entity with seed.",
        }),
        ["EntityPlayer"] = new("Entity", "Player entity. Most commonly used class for modding.", new[]
        {
            "player:GetName() — Returns player name (e.g., 'Isaac').",
            "player:GetPlayerType() — Returns PlayerType enum.",
            "player:GetCollectibleNum(collectible) — Returns count of a collectible.",
            "player:HasCollectible(collectible) — Returns true if player has collectible.",
            "player:HasTrinket(trinket) — Returns true if player has trinket.",
            "player:AddCollectible(collectible, charge, pool) — Adds a collectible to player.",
            "player:RemoveCollectible(collectible) — Removes a collectible.",
            "player:DropCollectible(collectible) — Drops a collectible on the floor.",
            "player:AnimatePickup(collectible) — Plays pickup animation.",
            "player:GetEffects() — Returns TemporaryEffects object.",
            "player:GetDamageMultiplier() — Returns damage multiplier.",
            "player:GetFireDelayModifier() — Returns fire delay modifier.",
            "player:GetTearDamage() — Returns tear damage value.",
            "player:GetTearRate() — Returns tear rate (shots per second).",
            "player:GetTearRange() — Returns tear range.",
            "player:GetTearSpeed() — Returns tear speed.",
            "player:GetTearFallingSpeed() — Returns tear falling speed.",
            "player:GetTearHeight() — Returns tear height.",
            "player:GetTearFlags() — Returns TearFlags bitmask.",
            "player:GetShootingSpeedModifier() — Returns shooting speed modifier.",
            "player:GetLuck() — Returns player luck value.",
            "player:GetHearts() — Returns red hearts (as float).",
            "player:GetMaxHearts() — Returns max red hearts (as int, 1 = half heart).",
            "player:GetSoulHearts() — Returns soul hearts.",
            "player:GetBlackHearts() — Returns black hearts.",
            "player:GetBoneHearts() — Returns bone hearts.",
            "player:GetGoldenHearts() — Returns golden hearts.",
            "player:GetEternalHearts() — Returns eternal hearts.",
            "player:GetRottenHearts() — Returns rotten hearts.",
            "player:AddHearts(hearts) — Adds red hearts.",
            "player:AddSoulHearts(hearts) — Adds soul hearts.",
            "player:AddBlackHearts(hearts) — Adds black hearts.",
            "player:AddMaxHearts(hearts, ignoreKeeper) — Adds max red hearts.",
            "player:FullHearts() — Fully heals red hearts.",
            "player:HealRedHearts(hearts) — Heals red hearts only.",
            "player:TakeDamage(damage, damageFlags, source, damageCountdown) — Deals damage to player.",
            "player:GetPosition() — Returns Vector position.",
            "player:GetVelocity() — Returns Vector velocity.",
            "player:SetPosition(pos) — Sets player position.",
            "player:Teleport(pos, effects) — Teleports player.",
            "player:GetSprite() — Returns Sprite object.",
            "player:GetBodyMoveDirection() — Returns Vector body move direction.",
            "player:GetShootingDirection() — Returns Vector shooting direction.",
            "player:CanFly() — Returns true if player can fly.",
            "player:CanShoot() — Returns true if player can shoot.",
            "player:CanPickRedHearts() — Returns true if player can pick red hearts.",
            "player:GetActiveItem() — Returns active item (slot 0).",
            "player:GetActiveItem(slot) — Returns active item by slot (0-3).",
            "player:SetActiveItem(collectible, slot, keep) — Sets active item.",
            "player:DischargeActiveItem(slot) — Discharges active item charge.",
            "player:GetActiveCharge(slot) — Returns active item charge.",
            "player:SetActiveCharge(charge, slot) — Sets active item charge.",
            "player:GetMaxPocketItems() — Returns max pocket items.",
            "player:GetPocketItem(idx) — Returns PocketItem.",
            "player:AddTrinket(trinket) — Adds a trinket.",
            "player:RemoveTrinket(trinket) — Removes a trinket.",
            "player:SmeltTrinket() — Smelts trinkets (combines duplicates into golden).",
            "player:UseActiveItem(collectible, useFlags) — Uses an active item.",
            "player:UseCard(card) — Uses a card.",
            "player:UsePill(pillEffect, pillColor) — Uses a pill.",
            "player:ThrowKnife(direction) — Throws knife (for Mom's Knife).",
            "player:GetPlayerType() — Returns PlayerType.",
            "player:ChangePlayerType(playerType) — Changes player type.",
            "player:GetControllerId() — Returns controller ID.",
            "player:GetMovementJoystick() — Returns movement joystick Vector.",
            "player:GetAimJoystick() — Returns aim joystick Vector.",
            "player:GetMovementInput() — Returns movement input Vector.",
            "player:GetShootingInput() — Returns shooting input Vector.",
            "player:PressButton(button) — Simulates button press.",
            "player:GetTearDisplacement() — Returns tear displacement.",
            "player:GetPlayerForm() — Returns PlayerForm (transformation).",
            "player:TryRemoveCollectible(collectible) — Tries to remove collectible, returns success.",
            "player:GetCollectibleRNG(collectible) — Returns RNG for collectible.",
            "player:GetCardRNG(card) — Returns RNG for card.",
            "player:GetPillRNG(pillEffect) — Returns RNG for pill.",
            "player:GetTrinketRNG(trinket) — Returns RNG for trinket.",
            "player:ClearQueueItem() — Clears queued item.",
            "player:IsItemQueueEmpty() — Returns true if item queue is empty.",
            "player:GetQueuedItem() — Returns queued item table.",
            "player:GetBabySkin() — Returns baby skin (co-op babies).",
            "player:HasFullHearts() — Returns true if at full red hearts.",
            "player:HasFullHeartsAndSoulHearts() — Returns true if at full HP.",
            "player:CanUsePill() — Returns true if can use pill.",
            "player:CanUseCard() — Returns true if can use card.",
            "player:GetDamageCooldown() — Returns damage cooldown frames.",
            "player:SetDamageCooldown(frames) — Sets damage cooldown.",
            "player:GetLastDamageFlags() — Returns last DamageFlags.",
            "player:GetLastDamageSource() — Returns last damage source EntityRef.",
            "player:GetLastDamageTime() — Returns last damage time (frame).",
        }),
        ["EntityNPC"] = new("Entity", "NPC entity for enemies, bosses, and friendly NPCs.", new[]
        {
            "npc:GetType() — Returns EntityType.",
            "npc:GetVariant() — Returns variant.",
            "npc:GetSubType() — Returns subtype.",
            "npc:GetPosition() — Returns Vector position.",
            "npc:GetVelocity() — Returns Vector velocity.",
            "npc:SetPosition(pos) — Sets position.",
            "npc:GetSprite() — Returns Sprite object.",
            "npc:GetHP() — Returns current HP.",
            "npc:GetMaxHitPoints() — Returns max HP.",
            "npc:SetHitPoints(hp) — Sets current HP.",
            "npc:AddHealth(hp) — Adds HP (can be negative for damage).",
            "npc:TakeDamage(damage, damageFlags, source, damageCountdown) — Deals damage.",
            "npc:Kill() — Kills the NPC.",
            "npc:Remove() — Removes the NPC from the game.",
            "npc:GetState() — Returns NPC state (for state machines).",
            "npc:SetState(state) — Sets NPC state.",
            "npc:GetPathFinder() — Returns PathFinder object.",
            "npc:GetTarget() — Returns target Entity.",
            "npc:SetTarget(entity) — Sets target entity.",
            "npc:MakeBloodPoof() — Creates blood poof effect.",
            "npc:MakeBloodPoof2() — Creates blood poof effect variant 2.",
            "npc:MakeMushroomPoof() — Creates mushroom poof effect.",
            "npc:GetBossID() — Returns BossID for bosses.",
            "npc:IsBoss() — Returns true if boss.",
            "npc:IsChampion() — Returns true if champion enemy.",
            "npc:GetChampionColorIdx() — Returns champion color index.",
            "npc:ToNPC() — Returns self as EntityNPC (type assertion).",
            "npc:GetShieldProbability() — Returns shield probability.",
            "npc:GetProjectileCooldown() — Returns projectile cooldown.",
            "npc:SetProjectileCooldown(cooldown) — Sets projectile cooldown.",
            "npc:GetScale() — Returns scale.",
            "npc:SetScale(scale) — Sets scale.",
            "npc:GetSize() — Returns size.",
            "npc:GetCollisionDamage() — Returns collision damage.",
            "npc:SetCollisionDamage(damage) — Sets collision damage.",
        }),
        ["Room"] = new("Game", "Current room data accessed via Game():GetRoom().", new[]
        {
            "room:GetType() — Returns RoomType.",
            "room:GetShape() — Returns RoomShape.",
            "room:GetGridIndex(pos) — Returns grid index for position.",
            "room:GetGridEntity(gridIndex) — Returns GridEntity at index.",
            "room:GetGridEntityFromPosition(pos) — Returns GridEntity at position.",
            "room:GetGridWidth() — Returns grid width.",
            "room:GetGridHeight() — Returns grid height.",
            "room:GetCenterPos() — Returns center Vector.",
            "room:GetTopLeftPos() — Returns top-left Vector.",
            "room:GetBottomRightPos() — Returns bottom-right Vector.",
            "room:GetRandomTileIndex(seed) — Returns random tile index.",
            "room:GetAliveBossCount() — Returns alive boss count.",
            "room:IsClear() — Returns true if room is cleared.",
            "room:IsFirstVisit() — Returns true if first visit.",
            "room:GetFrameCount() — Returns room frame count.",
            "room:GetDecorationIndex() — Returns decoration index.",
            "room:GetDoorSlot() — Returns door slot.",
            "room:GetDoor(slot) — Returns Door at slot.",
            "room:GetGridCollision(gridIndex) — Returns grid collision at index.",
            "room:GetWaterAmount() — Returns water amount.",
            "room:SetWaterAmount(amount) — Sets water amount.",
            "room:GetShockWaveParam() — Returns shockwave param.",
            "room:ShockWave(pos, radius, damage) — Creates shockwave.",
            "room:DamageGrid(gridIndex, damage) — Damages grid entity.",
            "room:RemoveGridEntity(gridIndex, pathTrail, keepDecoration) — Removes grid entity.",
            "room:SpawnGridEntity(gridIndex, type, variant, subtype, seed) — Spawns grid entity.",
            "room:SpawnEntity(type, variant, subtype, position, velocity) — Spawns entity in room.",
            "room:Update() — Updates the room.",
            "room:Render() — Renders the room.",
            "room:GetEntities() — Returns entities in room.",
            "room:IsAmbushActive() — Returns true if ambush (challenge room) active.",
            "room:GetAmbushDuration() — Returns ambush duration.",
            "room:GetAmbushWavesLeft() — Returns ambush waves remaining.",
            "room:StopAmbush() — Stops current ambush.",
            "room:IsLShapedRoom() — Returns true if L-shaped room.",
            "room:GetBrokenWallCount() — Returns broken wall count.",
            "room:GetFireAmount() — Returns fire amount.",
            "room:SetFireAmount(amount) — Sets fire amount.",
            "room:TryGetWaterAmount() — Tries to get water amount.",
            "room:TryGetLavaAmount() — Tries to get lava amount.",
            "room:TryGetWaterPitsAmount() — Tries to get water pits amount.",
        }),
        ["Level"] = new("Game", "Level data accessed via Game():GetLevel().", new[]
        {
            "level:GetCurrentRoomIndex() — Returns current room index.",
            "level:GetCurrentRoom() — Returns current Room.",
            "level:GetCurrentStage() — Returns current stage (1-13).",
            "level:GetCurrentStageType() — Returns StageType.",
            "level:GetRooms() — Returns Rooms (table of room descriptors).",
            "level:GetRoomByIdx(idx) — Returns room descriptor by index.",
            "level:GetNumRooms() — Returns number of rooms.",
            "level:ChangeRoom(roomIdx) — Changes to room by index.",
            "level:EnterDoor(doorSlot) — Enters through door slot.",
            "level:NextStage() — Advances to next stage.",
            "level:ShowMap() — Shows entire map.",
            "level:ShowName() — Shows room names.",
            "level:HideMap() — Hides map.",
            "level:ApplyMapState() — Applies map state.",
            "level:GetDungeonPlacementSeed() — Returns dungeon placement seed.",
            "level:GetEnterPosition() — Returns enter position Vector.",
            "level:GetLastRoomIndex() — Returns last room index.",
            "level:GetPreviousStageIndex() — Returns previous stage index.",
            "level:GetStage() — Returns current stage.",
            "level:SetStage(stage, stageType) — Sets stage and type.",
            "level:GetAbsoluteStage() — Returns absolute stage (includes Greed mode).",
            "level:GetDevilRoomChance() — Returns devil room chance (float 0-1).",
            "level:SetDevilRoomChance(chance) — Sets devil room chance.",
            "level:GetAngelRoomChance() — Returns angel room chance.",
            "level:SetAngelRoomChance(chance) — Sets angel room chance.",
            "level:InitializeDevilAngelRoom() — Initializes devil/angel room.",
            "level:ForceHorsemanBoss() — Forces horseman boss.",
            "level:HasBossChallenge() — Returns true if boss challenge active.",
            "level:GetStateFlag(flag) — Returns LevelStateFlag value.",
            "level:SetStateFlag(flag, value) — Sets LevelStateFlag.",
        }),
        ["Vector"] = new("Global", "2D vector used for positions, velocities, and directions.", new[]
        {
            "Vector(x, y) — Creates a new vector.",
            "Vector.Zero — (0, 0)",
            "Vector.One — (1, 1)",
            "Vector.Up — (0, -1)",
            "Vector.Down — (0, 1)",
            "Vector.Left — (-1, 0)",
            "Vector.Right — (1, 0)",
            "vec.X / vec.Y — Component access.",
            "vec:Length() — Returns vector length.",
            "vec:LengthSquared() — Returns squared length.",
            "vec:Normalized() — Returns normalized vector.",
            "vec:Rotated(angle) — Returns rotated vector (angle in radians).",
            "vec:Dot(other) — Returns dot product.",
            "vec:Cross(other) — Returns cross product (scalar in 2D).",
            "vec:Distance(other) — Returns distance to other vector.",
            "vec:Dist(other) — Alias for Distance.",
            "vec:Lerp(other, t) — Linear interpolation.",
            "vec:Resized(length) — Returns vector resized to given length.",
            "vec:Abs() — Returns vector with absolute components.",
            "vec:Floor() — Returns vector with floored components.",
            "vec:Ceil() — Returns vector with ceiling components.",
            "vec + other — Vector addition.",
            "vec - other — Vector subtraction.",
            "vec * scalar — Scalar multiplication.",
            "vec / scalar — Scalar division.",
            "-vec — Negation.",
        }),
        ["Sprite"] = new("Rendering", "Sprite object for rendering custom graphics and animations.", new[]
        {
            "sprite:GetCurrentAnimation() — Returns current animation name.",
            "sprite:Play(name, force) — Plays animation by name.",
            "sprite:SetAnimation(name) — Sets animation without playing.",
            "sprite:SetFrame(frame) — Sets current frame.",
            "sprite:GetFrame() — Returns current frame.",
            "sprite:IsPlaying(name) — Returns true if animation is playing.",
            "sprite:IsFinished(name) — Returns true if animation finished.",
            "sprite:Update() — Updates animation.",
            "sprite:Render(position) — Renders sprite at position.",
            "sprite:RenderLayer(layerId, position) — Renders specific layer.",
            "sprite:Load(filename, loadGraphics) — Loads ANM2 file.",
            "sprite:LoadGraphics() — Loads graphics for current ANM2.",
            "sprite:GetDefaultAnimation() — Returns default animation.",
            "sprite:SetDefaultAnimation(name) — Sets default animation.",
            "sprite:GetLayerCount() — Returns number of layers.",
            "sprite:GetLayer(layerId) — Returns layer by ID.",
            "sprite:ReplaceSpritesheet(layerId, filename) — Replaces spritesheet.",
            "sprite:LoadGraphics() — Reloads graphics.",
            "sprite:SetRenderFlags(flags) — Sets render flags.",
            "sprite:GetScale() — Returns scale Vector.",
            "sprite:SetScale(scale) — Sets scale Vector.",
            "sprite:GetRotation() — Returns rotation in degrees.",
            "sprite:SetRotation(degrees) — Sets rotation.",
            "sprite:GetPos() — Returns position Vector.",
            "sprite:SetPos(pos) — Sets position.",
            "sprite:GetColor() — Returns KColor.",
            "sprite:SetColor(color) — Sets KColor.",
            "sprite:GetAlpha() — Returns alpha (0-1).",
            "sprite:SetAlpha(alpha) — Sets alpha.",
            "sprite:Stop() — Stops current animation.",
            "sprite:SetLastFrame() — Jumps to last frame.",
            "sprite:Reset() — Resets sprite to default state.",
            "sprite:GetTexel() — Returns texel Vector.",
            "sprite:IsOverlayAnimated() — Returns true if overlay is animated.",
            "sprite:SetOverlayAnimation(name) — Sets overlay animation.",
            "sprite:PlayOverlay(name, force) — Plays overlay animation.",
            "sprite:IsOverlayPlaying(name) — Returns true if overlay playing.",
            "sprite:IsOverlayFinished() — Returns true if overlay finished.",
            "sprite:RenderOverlay(position) — Renders overlay at position.",
        }),
        ["TemporaryEffects"] = new("Entity", "Player temporary effects accessed via player:GetEffects().", new[]
        {
            "effects:AddCollectibleEffect(collectible, addCostume, count) — Adds collectible effect.",
            "effects:AddNullEffect(nullId, addCostume, count) — Adds null item effect.",
            "effects:AddTrinketEffect(trinket, addCostume, count) — Adds trinket effect.",
            "effects:RemoveCollectibleEffect(collectible, count) — Removes collectible effect.",
            "effects:RemoveNullEffect(nullId, count) — Removes null effect.",
            "effects:RemoveTrinketEffect(trinket, count) — Removes trinket effect.",
            "effects:GetCollectibleEffect(collectible) — Returns TemporaryEffect or nil.",
            "effects:GetNullEffect(nullId) — Returns TemporaryEffect or nil.",
            "effects:GetTrinketEffect(trinket) — Returns TemporaryEffect or nil.",
            "effects:HasCollectibleEffect(collectible) — Returns true if effect present.",
            "effects:GetCollectibleEffectNum(collectible) — Returns count of effect.",
            "effects:GetEffectsList() — Returns table of all effects.",
            "effects:ClearEffects() — Clears all effects.",
        }),
        ["Entity"] = new("Entity", "Base entity class. All entities inherit from this.", new[]
        {
            "entity:GetType() — Returns EntityType.",
            "entity:GetVariant() — Returns variant.",
            "entity:GetSubType() — Returns subtype.",
            "entity:GetPosition() — Returns Vector position.",
            "entity:GetVelocity() — Returns Vector velocity.",
            "entity:SetPosition(pos) — Sets position.",
            "entity:SetVelocity(vel) — Sets velocity.",
            "entity:GetSprite() — Returns Sprite object.",
            "entity:GetData() — Returns mod data table (persistent per entity).",
            "entity:GetDropState() — Returns drop state.",
            "entity:Remove() — Removes entity from game.",
            "entity:Kill() — Kills entity.",
            "entity:TakeDamage(damage, flags, source, countdown) — Deals damage.",
            "entity:GetHP() — Returns current HP.",
            "entity:GetMaxHitPoints() — Returns max HP.",
            "entity:ToPlayer() — Returns EntityPlayer or nil.",
            "entity:ToNPC() — Returns EntityNPC or nil.",
            "entity:ToPickup() — Returns EntityPickup or nil.",
            "entity:ToTear() — Returns EntityTear or nil.",
            "entity:ToProjectile() — Returns EntityProjectile or nil.",
            "entity:ToLaser() — Returns EntityLaser or nil.",
            "entity:ToKnife() — Returns EntityKnife or nil.",
            "entity:ToEffect() — Returns EntityEffect or nil.",
            "entity:ToFamiliar() — Returns EntityFamiliar or nil.",
            "entity:ToBomb() — Returns EntityBomb or nil.",
            "entity:GetCollisionDamage() — Returns collision damage.",
            "entity:GetSize() — Returns entity size.",
            "entity:GetScale() — Returns scale.",
            "entity:GetRenderZOffset() — Returns render Z offset.",
            "entity:GetPositionOffset() — Returns position offset Vector.",
            "entity:HasMortalDamage() — Returns true if entity has mortal damage.",
            "entity:IsDead() — Returns true if entity is dead.",
            "entity:IsVisible() — Returns true if visible.",
            "entity:SetVisible(visible) — Sets visibility.",
            "entity:IsVulnerableEnemy() — Returns true if vulnerable enemy.",
            "entity:Exists() — Returns true if entity still exists.",
            "entity:GetFriction() — Returns friction.",
            "entity:SetFriction(friction) — Sets friction.",
            "entity:GetMass() — Returns mass.",
            "entity:GetShadowSize() — Returns shadow size.",
            "entity:SetShadowSize(size) — Sets shadow size.",
            "entity:GetSpawnerEntity() — Returns spawner entity.",
            "entity:GetSpawnerType() — Returns spawner EntityType.",
            "entity:GetSpawnerVariant() — Returns spawner variant.",
            "entity:GetLastCollisionFrame() — Returns last collision frame.",
            "entity:GetCollisionGroup() — Returns collision group.",
            "entity:GetData() — Returns per-entity mod data table. Use for custom state.",
        }),
        ["EntityPickup"] = new("Entity", "Pickup entity (coins, hearts, keys, collectibles, etc.)", new[]
        {
            "pickup:GetVariant() — Returns pickup variant (PickupVariant).",
            "pickup:GetSubType() — Returns subtype (e.g., coin value, collectible ID).",
            "pickup:TryPickup(player) — Attempts pickup by player.",
            "pickup:IsShopItem() — Returns true if shop item.",
            "pickup:GetPrice() — Returns price (for shop items).",
            "pickup:SetPrice(price) — Sets price.",
            "pickup:PlayPickupSound() — Plays pickup sound.",
            "pickup:TryRemoveCollectible() — Tries to remove collectible.",
            "pickup:WaitForPlayerDeathAnimation() — Waits for player death animation.",
            "pickup:GetTouched() — Returns true if touched.",
            "pickup:SetTouched(touched) — Sets touched state.",
            "pickup:MakeShopItem(price) — Makes this pickup a shop item.",
            "pickup:GetCharge() — Returns charge (for collectible pickups).",
            "pickup:SetCharge(charge) — Sets charge.",
            "pickup:Remove() — Removes the pickup.",
            "pickup:ToPickup() — Returns self as EntityPickup.",
            "pickup:CanPickup(player) — Returns true if can be picked up by player.",
            "pickup:CollideWithPlayer(player) — Handles collision with player.",
        }),
        ["EntityTear"] = new("Entity", "Tear entity for player and enemy projectiles.", new[]
        {
            "tear:GetVariant() — Returns tear variant.",
            "tear:GetScale() — Returns scale.",
            "tear:SetScale(scale) — Sets scale.",
            "tear:GetDamage() — Returns damage value.",
            "tear:SetDamage(damage) — Sets damage.",
            "tear:GetTearFlags() — Returns TearFlags.",
            "tear:SetTearFlags(flags) — Sets TearFlags.",
            "tear:GetColor() — Returns KColor.",
            "tear:SetColor(color) — Sets KColor.",
            "tear:GetSpawnerEntity() — Returns spawner entity.",
            "tear:GetSpawnerType() — Returns spawner type.",
            "tear:GetSpawnerVariant() — Returns spawner variant.",
            "tear:GetHeight() — Returns tear height.",
            "tear:SetHeight(height) — Sets tear height.",
            "tear:GetFallingSpeed() — Returns falling speed.",
            "tear:SetFallingSpeed(speed) — Sets falling speed.",
            "tear:GetBaseDamage() — Returns base damage.",
            "tear:GetBaseSpeed() — Returns base speed.",
            "tear:GetBaseRange() — Returns base range.",
            "tear:GetBaseHeight() — Returns base height.",
            "tear:GetBaseFallingSpeed() — Returns base falling speed.",
            "tear:GetTearShape() — Returns TearShape.",
            "tear:SetTearShape(shape) — Sets tear shape.",
            "tear:GetPosition() — Returns position Vector.",
            "tear:GetVelocity() — Returns velocity Vector.",
            "tear:Remove() — Removes the tear.",
            "tear:ToTear() — Returns self as EntityTear.",
        }),
        ["EntityEffect"] = new("Entity", "Effect entity for visual effects, poofs, and custom effects.", new[]
        {
            "effect:GetVariant() — Returns effect variant (EffectVariant).",
            "effect:GetSubType() — Returns subtype.",
            "effect:GetState() — Returns effect state.",
            "effect:SetState(state) — Sets effect state.",
            "effect:GetScale() — Returns scale.",
            "effect:SetScale(scale) — Sets scale.",
            "effect:GetSprite() — Returns Sprite object.",
            "effect:GetPosition() — Returns position Vector.",
            "effect:GetVelocity() — Returns velocity Vector.",
            "effect:SetPosition(pos) — Sets position.",
            "effect:SetVelocity(vel) — Sets velocity.",
            "effect:Remove() — Removes the effect.",
            "effect:ToEffect() — Returns self as EntityEffect.",
            "effect:GetLifeSpan() — Returns life span.",
            "effect:SetLifeSpan(frames) — Sets life span.",
            "effect:GetMaxLifeSpan() — Returns max life span.",
            "effect:GetTimeout() — Returns timeout frames.",
            "effect:SetTimeout(frames) — Sets timeout frames.",
        }),
        ["EntityFamiliar"] = new("Entity", "Familiar entity (followers, orbitals, etc.)", new[]
        {
            "familiar:GetVariant() — Returns familiar variant (FamiliarVariant).",
            "familiar:GetSubType() — Returns subtype.",
            "familiar:GetPlayer() — Returns owner EntityPlayer.",
            "familiar:GetState() — Returns familiar state.",
            "familiar:SetState(state) — Sets familiar state.",
            "familiar:GetPathFinder() — Returns PathFinder.",
            "familiar:GetTarget() — Returns target Entity.",
            "familiar:SetTarget(entity) — Sets target.",
            "familiar:GetSprite() — Returns Sprite object.",
            "familiar:GetPosition() — Returns position Vector.",
            "familiar:GetVelocity() — Returns velocity Vector.",
            "familiar:Remove() — Removes the familiar.",
            "familiar:ToFamiliar() — Returns self as EntityFamiliar.",
            "familiar:FireProjectile(direction) — Fires projectile from familiar.",
            "familiar:GetCharge() — Returns charge.",
            "familiar:SetCharge(charge) — Sets charge.",
            "familiar:GetCooldown() — Returns cooldown.",
            "familiar:SetCooldown(cooldown) — Sets cooldown.",
        }),
        ["EntityBomb"] = new("Entity", "Bomb entity.", new[]
        {
            "bomb:GetVariant() — Returns bomb variant (BombVariant).",
            "bomb:GetFlags() — Returns TearFlags for bomb.",
            "bomb:SetFlags(flags) — Sets TearFlags.",
            "bomb:GetDamage() — Returns bomb damage.",
            "bomb:SetDamage(damage) — Sets bomb damage.",
            "bomb:GetRadius() — Returns explosion radius.",
            "bomb:SetRadius(radius) — Sets explosion radius.",
            "bomb:GetScale() — Returns scale.",
            "bomb:SetScale(scale) — Sets scale.",
            "bomb:GetExplosionCountdown() — Returns countdown to explosion.",
            "bomb:SetExplosionCountdown(frames) — Sets countdown.",
            "bomb:IsExploding() — Returns true if exploding.",
            "bomb:IsLandmine() — Returns true if landmine.",
            "bomb:IsGiga() — Returns true if giga bomb.",
            "bomb:Remove() — Removes the bomb.",
            "bomb:ToBomb() — Returns self as EntityBomb.",
        }),
        ["EntityProjectile"] = new("Entity", "Projectile entity for enemy projectiles.", new[]
        {
            "projectile:GetVariant() — Returns projectile variant.",
            "projectile:GetDamage() — Returns damage.",
            "projectile:SetDamage(damage) — Sets damage.",
            "projectile:GetScale() — Returns scale.",
            "projectile:SetScale(scale) — Sets scale.",
            "projectile:GetColor() — Returns KColor.",
            "projectile:SetColor(color) — Sets KColor.",
            "projectile:GetSpawnerEntity() — Returns spawner entity.",
            "projectile:GetSpawnerType() — Returns spawner type.",
            "projectile:GetHeight() — Returns height.",
            "projectile:SetHeight(height) — Sets height.",
            "projectile:GetFallingSpeed() — Returns falling speed.",
            "projectile:SetFallingSpeed(speed) — Sets falling speed.",
            "projectile:GetProjectileFlags() — Returns ProjectileFlags.",
            "projectile:SetProjectileFlags(flags) — Sets ProjectileFlags.",
            "projectile:Remove() — Removes the projectile.",
            "projectile:ToProjectile() — Returns self as EntityProjectile.",
        }),
        ["EntityKnife"] = new("Entity", "Knife entity (Mom's Knife, etc.)", new[]
        {
            "knife:GetVariant() — Returns knife variant.",
            "knife:GetDamage() — Returns damage.",
            "knife:SetDamage(damage) — Sets damage.",
            "knife:GetSprite() — Returns Sprite object.",
            "knife:GetPosition() — Returns position Vector.",
            "knife:GetVelocity() — Returns velocity Vector.",
            "knife:Remove() — Removes the knife.",
            "knife:ToKnife() — Returns self as EntityKnife.",
            "knife:GetRotation() — Returns rotation.",
            "knife:SetRotation(rotation) — Sets rotation.",
        }),
        ["EntityLaser"] = new("Entity", "Laser entity for laser tears.", new[]
        {
            "laser:GetVariant() — Returns laser variant (LaserVariant).",
            "laser:GetDamage() — Returns damage.",
            "laser:SetDamage(damage) — Sets damage.",
            "laser:GetScale() — Returns scale.",
            "laser:SetScale(scale) — Sets scale.",
            "laser:GetColor() — Returns KColor.",
            "laser:SetColor(color) — Sets KColor.",
            "laser:GetTearFlags() — Returns TearFlags.",
            "laser:SetTearFlags(flags) — Sets TearFlags.",
            "laser:GetStartPos() — Returns start position Vector.",
            "laser:GetEndPoint() — Returns end position Vector.",
            "laser:SetMaxDistance(distance) — Sets max distance.",
            "laser:GetAngle() — Returns angle in radians.",
            "laser:SetAngle(angle) — Sets angle.",
            "laser:GetSampleMode() — Returns sample mode.",
            "laser:GetHomingDirection() — Returns homing direction Vector.",
            "laser:GetShooter() — Returns shooter Entity.",
            "laser:SetShooter(entity) — Sets shooter entity.",
            "laser:Remove() — Removes the laser.",
            "laser:ToLaser() — Returns self as EntityLaser.",
            "laser:IsMultidimensionalTouched() — Returns true if multidimensional touched.",
            "laser:ActivateLight(damage) — Activates light effect.",
            "laser:Discharge(targetPos) — Discharges laser to target.",
        }),
        ["RNG"] = new("Utility", "Random number generator for deterministic mod behavior.", new[]
        {
            "RNG() — Creates new RNG.",
            "rng:SetSeed(seed, shift) — Sets seed.",
            "rng:Next() — Returns random integer.",
            "rng:Next(min, max) — Returns random integer in range [min, max].",
            "rng:NextFloat() — Returns random float [0, 1).",
            "rng:RandomInt(max) — Returns random integer [0, max).",
            "rng:RandomFloat() — Returns random float [0, 1).",
            "rng:GetSeed() — Returns current seed.",
            "rng:FloatRange(min, max) — Returns random float in range.",
            "rng:IntRange(min, max) — Returns random int in range.",
        }),
        ["KColor"] = new("Rendering", "Color object with RGBA components.", new[]
        {
            "KColor(r, g, b, a) — Creates color (0-1 range).",
            "KColor.White — (1, 1, 1, 1)",
            "KColor.Black — (0, 0, 0, 1)",
            "KColor.Red — (1, 0, 0, 1)",
            "KColor.Green — (0, 1, 0, 1)",
            "KColor.Blue — (0, 0, 1, 1)",
            "KColor.Yellow — (1, 1, 0, 1)",
            "KColor.Cyan — (0, 1, 1, 1)",
            "KColor.Magenta — (1, 0, 1, 1)",
            "KColor.Orange — (1, 0.5, 0, 1)",
            "color.Red / .Green / .Blue / .Alpha — Component access.",
        }),
        ["Input"] = new("Global", "Input handling for player controls.", new[]
        {
            "Input.IsButtonPressed(button, controllerId) — Returns true if button is pressed.",
            "Input.IsButtonTriggered(button, controllerId) — Returns true on press frame.",
            "Input.IsButtonReleased(button, controllerId) — Returns true on release frame.",
            "Input.GetActionValue(button, controllerId) — Returns analog value (0-1).",
            "Input.IsActionPressed(button, controllerId) — Returns true if action pressed.",
            "Input.IsActionTriggered(button, controllerId) — Returns true on action press.",
            "Input.IsActionReleased(button, controllerId) — Returns true on action release.",
            "Input.GetMousePosition(onScreen) — Returns mouse position Vector.",
            "Input.IsMouseBtnPressed(button) — Returns true if mouse button pressed.",
            "Input.GetJoystickAxis(controllerId, axis) — Returns joystick axis value.",
            "Input.GetControllerIndexType(controllerId) — Returns controller type.",
        }),
        ["Color"] = new("Rendering", "Legacy color object (use KColor when possible).", new[]
        {
            "Color(r, g, b, a) — Creates color (0-1 range).",
            "Color.Default — Default color.",
            "color:Reset() — Resets to default.",
            "color:SetTint(r, g, b, a) — Sets tint.",
            "color:GetTint() — Returns tint values.",
            "color:GetColor() — Returns KColor equivalent.",
            "color:SetColor(kcolor) — Sets from KColor.",
        }),
        ["EntityRef"] = new("Utility", "Reference to an entity used in damage callbacks.", new[]
        {
            "EntityRef(entity) — Creates reference from entity.",
            "ref.Entity — Returns referenced Entity or nil.",
            "ref.Type — Returns EntityType.",
            "ref.Variant — Returns variant.",
            "ref.SubType — Returns subtype.",
            "ref:IsPlayer() — Returns true if references a player.",
            "ref:IsEnemy() — Returns true if references an enemy.",
            "ref:IsFriendly() — Returns true if references a friendly entity.",
        }),
        ["GridEntity"] = new("Grid", "Grid entity (rocks, pits, doors, etc.)", new[]
        {
            "grid:GetType() — Returns GridEntityType.",
            "grid:GetVariant() — Returns variant.",
            "grid:GetState() — Returns state.",
            "grid:SetState(state) — Sets state.",
            "grid:GetDesc() — Returns grid descriptor.",
            "grid:GetPosition() — Returns position Vector.",
            "grid:GetGridIndex() — Returns grid index.",
            "grid:Destroy(damage) — Destroys the grid entity.",
            "grid:ToRock() — Returns GridEntityRock or nil.",
            "grid:ToPit() — Returns GridEntityPit or nil.",
            "grid:ToDoor() — Returns GridEntityDoor or nil.",
            "grid:ToPressurePlate() — Returns GridEntityPressurePlate or nil.",
            "grid:ToDecoration() — Returns GridEntityDecoration or nil.",
            "grid:ToFire() — Returns GridEntityFire or nil.",
            "grid:ToSpikes() — Returns GridEntitySpikes or nil.",
            "grid:ToTNT() — Returns GridEntityTNT or nil.",
            "grid:ToPoop() — Returns GridEntityPoop or nil.",
            "grid:ToTrapDoor() — Returns GridEntityTrapDoor or nil.",
            "grid:ToStairs() — Returns GridEntityStairs or nil.",
        }),
        ["Seeds"] = new("Game", "Seed management accessed via Game():GetSeeds().", new[]
        {
            "seeds:GetStartSeedString() — Returns seed string.",
            "seeds:GetCurrentSeedString() — Returns current seed string.",
            "seeds:SetStartSeed(seedString) — Sets the start seed.",
            "seeds:IsCustomSeed() — Returns true if custom seed.",
            "seeds:GetSeed() — Returns numeric seed.",
            "seeds:Reset() — Resets seeds.",
            "seeds:GetChallenge() — Returns challenge ID.",
            "seeds:SetChallenge(challenge) — Sets challenge.",
        }),
        ["ItemPool"] = new("Game", "Item pool management accessed via Game():GetItemPool().", new[]
        {
            "pool:GetCollectible(itemPoolType, decrease, seed) — Returns a collectible from pool.",
            "pool:RemoveCollectible(collectible) — Removes collectible from all pools.",
            "pool:AddRoomBlacklist(collectible) — Blacklists collectible for current room.",
            "pool:IsBlacklisted(collectible) — Returns true if blacklisted.",
            "pool:GetCard(seed, allowNonCards) — Returns a card.",
            "pool:GetCardEx(seed, runeOnly, allowNonCards, allowModifiers) — Returns card with options.",
            "pool:GetTrinket(seed) — Returns a trinket.",
            "pool:GetPill(seed) — Returns a pill color.",
            "pool:UnidentifyPill(pillColor) — Unidentifies a pill.",
            "pool:CanIdentifyPill(pillColor) — Returns true if pill can be identified.",
            "pool:ForceAddCustomCollectibleToPool(collectible, poolType) — Forces collectible into pool.",
        }),
    };

    public record ClassInfo(string Category, string Description, string[] Methods);
}
