namespace IsaacAgent.Core.Knowledge;

public static class ModCallbacks
{
    public static readonly Dictionary<string, CallbackInfo> Callbacks = new()
    {
        ["MC_NPC_UPDATE"] = new(0, "EntityNPC", "EntityType", "Called every update frame for NPCs. Use OptionalArgs to filter by entity type."),
        ["MC_POST_UPDATE"] = new(1, "nil", "nil", "Called every update frame (30fps). No arguments. Use for constant effects."),
        ["MC_POST_RENDER"] = new(2, "nil", "nil", "Called every render frame. Use for rendering custom graphics."),
        ["MC_USE_ITEM"] = new(3, "EntityPlayer, UseFlags", "CollectibleType", "Called when a collectible item is used. Return false to prevent use."),
        ["MC_POST_EFFECT_UPDATE"] = new(4, "EntityEffect", "EntityType", "Called every update frame for effects."),
        ["MC_POST_PLAYER_INIT"] = new(5, "EntityPlayer", "nil", "Called when a player entity is initialized."),
        ["MC_USE_PILL"] = new(6, "EntityPlayer, UseFlags, PillColor", "PillEffect", "Called when a pill is used."),
        ["MC_POST_PEFFECT_UPDATE"] = new(7, "EntityPlayer", "nil", "Called every update frame for player effects."),
        ["MC_POST_PLAYER_UPDATE"] = new(8, "EntityPlayer", "nil", "Called every update frame for players."),
        ["MC_POST_PLAYER_RENDER"] = new(9, "EntityPlayer", "nil", "Called when rendering a player."),
        ["MC_PRE_PLAYER_COLLISION"] = new(10, "EntityPlayer, EntityCollider", "nil", "Called before player collision. Return true to skip vanilla collision."),
        ["MC_POST_PICKUP_INIT"] = new(11, "EntityPickup", "nil", "Called when a pickup is initialized."),
        ["MC_POST_PICKUP_UPDATE"] = new(12, "EntityPickup", "nil", "Called every update frame for pickups."),
        ["MC_POST_PICKUP_RENDER"] = new(13, "EntityPickup", "nil", "Called when rendering a pickup."),
        ["MC_POST_PICKUP_SELECTION"] = new(14, "EntityPickup, int, int", "nil", "Called to determine pickup selection. Return variant and subtype."),
        ["MC_PRE_PICKUP_COLLISION"] = new(15, "EntityPickup, EntityCollider", "nil", "Called before pickup collision. Return true to skip vanilla collision."),
        ["MC_POST_TEAR_INIT"] = new(16, "EntityTear", "nil", "Called when a tear is initialized."),
        ["MC_POST_TEAR_UPDATE"] = new(17, "EntityTear", "nil", "Called every update frame for tears."),
        ["MC_POST_TEAR_RENDER"] = new(18, "EntityTear", "nil", "Called when rendering a tear."),
        ["MC_PRE_TEAR_COLLISION"] = new(19, "EntityTear, EntityCollider", "nil", "Called before tear collision. Return true to skip vanilla collision."),
        ["MC_POST_PROJECTILE_INIT"] = new(20, "EntityProjectile", "nil", "Called when a projectile is initialized."),
        ["MC_POST_PROJECTILE_UPDATE"] = new(21, "EntityProjectile", "nil", "Called every update frame for projectiles."),
        ["MC_POST_PROJECTILE_RENDER"] = new(22, "EntityProjectile", "nil", "Called when rendering a projectile."),
        ["MC_PRE_PROJECTILE_COLLISION"] = new(23, "EntityProjectile, EntityCollider", "nil", "Called before projectile collision. Return true to skip vanilla collision."),
        ["MC_POST_LASER_INIT"] = new(24, "EntityLaser", "nil", "Called when a laser is initialized."),
        ["MC_POST_LASER_UPDATE"] = new(25, "EntityLaser", "nil", "Called every update frame for lasers."),
        ["MC_POST_LASER_RENDER"] = new(26, "EntityLaser", "nil", "Called when rendering a laser."),
        ["MC_POST_KNIFE_INIT"] = new(27, "EntityKnife", "nil", "Called when a knife is initialized."),
        ["MC_POST_KNIFE_UPDATE"] = new(28, "EntityKnife", "nil", "Called every update frame for knives."),
        ["MC_POST_KNIFE_RENDER"] = new(29, "EntityKnife", "nil", "Called when rendering a knife."),
        ["MC_PRE_KNIFE_COLLISION"] = new(30, "EntityKnife, EntityCollider", "nil", "Called before knife collision. Return true to skip vanilla collision."),
        ["MC_POST_FIRE_TEAR"] = new(31, "EntityTear", "nil", "Called when a tear is fired."),
        ["MC_POST_BOMB_INIT"] = new(32, "EntityBomb", "nil", "Called when a bomb is initialized."),
        ["MC_POST_BOMB_UPDATE"] = new(33, "EntityBomb", "nil", "Called every update frame for bombs."),
        ["MC_POST_BOMB_RENDER"] = new(34, "EntityBomb", "nil", "Called when rendering a bomb."),
        ["MC_PRE_BOMB_COLLISION"] = new(35, "EntityBomb, EntityCollider", "nil", "Called before bomb collision. Return true to skip vanilla collision."),
        ["MC_PRE_GET_COLLECTIBLE"] = new(36, "table", "nil", "Called when the game selects a collectible. Return CollectibleType to override."),
        ["MC_POST_GET_COLLECTIBLE"] = new(37, "CollectibleType", "nil", "Called after a collectible is selected."),
        ["MC_GET_PILL_COLOR"] = new(38, "PillColor", "nil", "Called to determine pill color. Return PillColor to override."),
        ["MC_GET_PILL_EFFECT"] = new(39, "PillEffect", "nil", "Called to determine pill effect. Return PillEffect to override."),
        ["MC_GET_TRINKET"] = new(40, "TrinketType", "nil", "Called to determine trinket. Return TrinketType to override."),
        ["MC_POST_ENTITY_REMOVE"] = new(41, "Entity", "EntityType", "Called when an entity is removed."),
        ["MC_POST_ENTITY_KILL"] = new(42, "Entity", "EntityType", "Called when an entity is killed."),
        ["MC_PRE_NPC_UPDATE"] = new(43, "EntityNPC", "EntityType", "Called before NPC update. Return true to skip vanilla update."),
        ["MC_PRE_SPAWN_CLEAN_AWARD"] = new(44, "Entity", "nil", "Called before spawning clean award. Return true to skip."),
        ["MC_PRE_ROOM_ENTITY_SPAWN"] = new(45, "table", "nil", "Called before room entity spawn. Return table to override."),
        ["MC_POST_GAME_STARTED"] = new(46, "boolean", "nil", "Called when a game starts. Boolean indicates if it's a continue."),
        ["MC_POST_GAME_END"] = new(47, "boolean", "nil", "Called when a game ends. Boolean indicates if it's from a continue."),
        ["MC_PRE_GAME_EXIT"] = new(48, "boolean", "nil", "Called before game exits. Boolean indicates if it's from a continue."),
        ["MC_POST_NEW_LEVEL"] = new(49, "nil", "nil", "Called when entering a new level."),
        ["MC_POST_NEW_ROOM"] = new(50, "nil", "nil", "Called when entering a new room."),
        ["MC_GET_CARD"] = new(51, "Card", "nil", "Called to determine card. Return Card to override."),
        ["MC_GET_TRINKET2"] = new(52, "TrinketType", "nil", "Called to determine trinket (variant 2). Return TrinketType to override."),
        ["MC_POST_CURSE_EVAL"] = new(53, "Curses", "nil", "Called to evaluate curse. Return Curses to override."),
        ["MC_POST_INPUT_ACTION"] = new(54, "Entity, InputHook, int", "nil", "Called for input actions. Return value to override input."),
        ["MC_EXECUTE_CMD"] = new(55, "string, table", "nil", "Called when a console command is executed. Return string to output."),
        ["MC_PRE_USE_ITEM"] = new(56, "EntityPlayer, UseFlags", "CollectibleType", "Called before item use. Return false to prevent use."),
        ["MC_PRE_ENTITY_SPAWN"] = new(57, "table", "nil", "Called before entity spawn. Return table to override."),
        ["MC_POST_FAMILIAR_RENDER"] = new(58, "EntityFamiliar", "nil", "Called when rendering a familiar."),
        ["MC_POST_NPC_INIT"] = new(59, "EntityNPC", "EntityType", "Called when an NPC is initialized."),
        ["MC_POST_NPC_RENDER"] = new(60, "EntityNPC", "EntityType", "Called when rendering an NPC."),
        ["MC_POST_NPC_DEATH"] = new(61, "EntityNPC", "EntityType", "Called when an NPC dies."),
        ["MC_PRE_NPC_COLLISION"] = new(62, "EntityNPC, EntityCollider", "EntityType", "Called before NPC collision. Return true to skip vanilla collision."),
        ["MC_GET_DEVIL_ROOM_DEAL"] = new(63, "table", "nil", "Called to determine devil room deal. Return table to override."),
        ["MC_POST_PICKUP_GET_DEVIL_ROOM_DEAL"] = new(64, "EntityPickup", "nil", "Called after pickup devil room deal."),
        ["MC_POST_PLAYER_NEW_ROOM_TEMP_EFFECTS"] = new(65, "EntityPlayer", "nil", "Called for player new room temp effects."),
        ["MC_POST_PLAYER_NEW_LEVEL"] = new(66, "EntityPlayer", "nil", "Called when player enters new level."),
        ["MC_POST_PLAYER_ADD_COLLECTIBLE"] = new(67, "EntityPlayer, CollectibleType", "nil", "Called after a collectible is added to player (REPENTOGON only)."),
        ["MC_PRE_FAMILIAR_RENDER"] = new(68, "EntityFamiliar", "Variant", "Called before familiar render. Return Vector to offset render position."),
        ["MC_POST_PLAYER_TAKE_DMG"] = new(69, "EntityPlayer, float, DamageFlags, EntityRef, int", "nil", "Called when player takes damage. Return false to prevent damage."),
        ["MC_POST_PLAYER_APPLY_INNATE_COLLECTIBLE_BONUS"] = new(70, "EntityPlayer, CollectibleType, int", "nil", "Called for innate collectible bonus."),
        ["MC_PRE_DEVIL_ROOM_ITEM"] = new(71, "table", "nil", "Called before devil room item selection. Return table to override."),
        ["MC_PRE_ANGLE_ROOM_ITEM"] = new(72, "table", "nil", "Called before angel room item selection. Return table to override."),
        ["MC_POST_PLAYER_CHECK_REVIVE_HEART"] = new(73, "EntityPlayer", "nil", "Called for player revive heart check."),
    };

    public record CallbackInfo(int Id, string Args, string OptionalArgs, string Description);
}
